AppBundle\Entity\ClanRole:
    exclusion_policy: ALL
    accessor_order: alphabetical
    properties:
        primaryRole:
            expose: true
        secondaryRole:
            expose: true
        clan:
            expose: true
